spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  profiles:
    active: dev
  application:
    name: kx-fram-core
    version: 1.0.0
  output:
    ansi:
      enabled: always
#mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml



